title: "Cospute: what is intelligence?"
description: "We're trying to understand the nature of intelligence"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # your site's URL

# Build settings
markdown: kramdown

# Collections
collections:
  q:
    output: true
    permalink: /q/:name/

# Defaults
defaults:
  - scope:
      path: "_q"
      type: "q"
    values:
      layout: "post"
