title: My Card Gallery
description: A grid of content cards
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # your site's URL

# Build settings
markdown: kramdown

# Collections
collections:
  q:
    output: true
    permalink: /q/:name/

# Defaults
defaults:
  - scope:
      path: "_q"
      type: "q"
    values:
      layout: "post"
